# Airthmetic Operation

In [7]:
import pandas as pd

In [8]:
var = pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,10]})
var

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

# Addition Operation

In [9]:
var["C"] = var["A"] + var["B"]
var

   A   B   C
0  1   6   7
1  2   7   9
2  3   8  11
3  4   9  13
4  5  10  15

# Subtraction Operation

In [10]:
var["D"] = var["A"] - var["B"]
var

   A   B   C  D
0  1   6   7 -5
1  2   7   9 -5
2  3   8  11 -5
3  4   9  13 -5
4  5  10  15 -5

# Multiplication Operation

In [12]:
var["E"] = var["A"] * var["B"]
var

   A   B   C  D   E
0  1   6   7 -5   6
1  2   7   9 -5  14
2  3   8  11 -5  24
3  4   9  13 -5  36
4  5  10  15 -5  50

# Division Operation

In [15]:
var['F'] = var['A'] / var['B']
var

   A   B   C  D   E         F
0  1   6   7 -5   6  0.166667
1  2   7   9 -5  14  0.285714
2  3   8  11 -5  24  0.375000
3  4   9  13 -5  36  0.444444
4  5  10  15 -5  50  0.500000

# Logical Operations

In [16]:
var1 =pd.DataFrame({'A':[10,20,30,40,50],'B':[16,17,18,19,10]})
var1

    A   B
0  10  16
1  20  17
2  30  18
3  40  19
4  50  10

In [20]:
var1['python'] = var1['A'] <= 20
var1['python_1'] = var1['B'] > 16
var1

    A   B  python  python_1
0  10  16    True     False
1  20  17    True      True
2  30  18   False      True
3  40  19   False      True
4  50  10   False     False