# write csv File

In [56]:
import pandas as pd

In [57]:
dic = {"name":['jeevanshu','visu','abhibnav','yash','kallu'], "marks":[80,70,85,65,90], "grade" :['b','c','b','d','a'],"rank":[3,4,2,5,1]} #length of both dic must be equal
var1 = pd.DataFrame(dic)
print(var1)

var1.to_csv('test.csv',index = False,header=True)

        name  marks grade  rank
0  jeevanshu     80     b     3
1       visu     70     c     4
2   abhibnav     85     b     2
3       yash     65     d     5
4      kallu     90     a     1

# Read CSV

In [58]:
csv_1 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv")
csv_1

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
4,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [59]:
csv_2 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",nrows=6,usecols=[1,4]) # num of rows , num of columns
csv_2

  Customer_Name     Product
0  Aarav Sharma      Laptop
1  Ananya Patel     T-Shirt
2   Rohan Verma  Smartphone
3   Priya Singh     Blender
4  Vikram Gupta  Headphones
5    Neha Reddy       Jeans

In [60]:
csv_3 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",skiprows=[0,5,7]) # skip  rows
csv_3

,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0.1
0,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
1,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
2,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
3,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
4,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
5,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
6,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
7,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
8,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
9,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
10,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
11,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [61]:
csv_4 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",index_col="City") # kisi bhi col ko index bana sakte hai
csv_4

,Transaction_ID,Customer_Name,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
City,,,,,,,,,,
Delhi,1001,Aarav Sharma,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
Mumbai,1002,Ananya Patel,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
Bengaluru,1003,Rohan Verma,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
Delhi,1004,Priya Singh,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
Hyderabad,1005,Vikram Gupta,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
Bengaluru,1006,Neha Reddy,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
Mumbai,1007,Karan Malhotra,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
Chennai,1008,Sanya Iyer,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
Kolkata,1009,Rahul Das,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
Pune,1010,Meera Joshi,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
Delhi,1011,Amit Kumar,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
Mumbai,1012,Pooja Hegde,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
Bengaluru,1013,Siddharth Roy,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
Hyderabad,1014,Riya Sen,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
Pune,1015,Deepak Verma,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [62]:
csv_5 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",header=2) # 2 row become header
csv_5

,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
0,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
1,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
2,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
3,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
4,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
5,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
6,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
7,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
8,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
9,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
10,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
11,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
12,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [ ]:
csv_6 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",usecols=[1,3,4],names=["col1","col2","col3"]) # add names
csv_6

              col1            col2          col3
0    Customer_Name        Category       Product
1     Aarav Sharma     Electronics        Laptop
2     Ananya Patel        Clothing       T-Shirt
3      Rohan Verma     Electronics    Smartphone
4      Priya Singh  Home & Kitchen       Blender
5     Vikram Gupta     Electronics    Headphones
6       Neha Reddy        Clothing         Jeans
7   Karan Malhotra  Home & Kitchen     Microwave
8       Sanya Iyer     Electronics    Smartwatch
9        Rahul Das        Clothing        Jacket
10     Meera Joshi  Home & Kitchen     Air Fryer
11      Amit Kumar     Electronics        Tablet
12     Pooja Hegde        Clothing         Dress
13   Siddharth Roy     Electronics       Monitor
14        Riya Sen  Home & Kitchen  Coffee Maker
15    Deepak Verma        Clothing         Shirt

In [ ]:
csv_7 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",header=None, ).add_prefix("col") # add prefix to column names
csv_7

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10
0,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
1,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
2,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
3,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
4,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
5,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
6,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
7,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
8,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
9,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
10,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
11,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
12,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
13,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
14,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
15,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0

In [70]:
csv_8 = pd.read_csv("C:\\Users\\YOGA\\Downloads\\pandas_practice_data.csv",dtype={'Price':'float'})
csv_8

,Transaction_ID,Customer_Name,City,Category,Product,Price,Quantity,Payment_Method,Order_Date,Rating,Total_Amount
0,1001,Aarav Sharma,Delhi,Electronics,Laptop,55000.0,1,UPI,2024-01-15,4.5,55000.0
1,1002,Ananya Patel,Mumbai,Clothing,T-Shirt,1200.0,3,Credit Card,2024-01-18,4.0,3600.0
2,1003,Rohan Verma,Bengaluru,Electronics,Smartphone,25000.0,1,UPI,2024-01-20,4.8,25000.0
3,1004,Priya Singh,Delhi,Home & Kitchen,Blender,3500.0,2,Debit Card,2024-01-22,3.9,7000.0
4,1005,Vikram Gupta,Hyderabad,Electronics,Headphones,2500.0,2,Net Banking,2024-01-25,4.2,5000.0
5,1006,Neha Reddy,Bengaluru,Clothing,Jeans,2200.0,1,UPI,2024-01-28,4.1,2200.0
6,1007,Karan Malhotra,Mumbai,Home & Kitchen,Microwave,6500.0,1,Credit Card,2024-02-02,4.6,6500.0
7,1008,Sanya Iyer,Chennai,Electronics,Smartwatch,4500.0,1,UPI,2024-02-05,4.3,4500.0
8,1009,Rahul Das,Kolkata,Clothing,Jacket,3800.0,2,Debit Card,2024-02-10,3.8,7600.0
9,1010,Meera Joshi,Pune,Home & Kitchen,Air Fryer,5200.0,1,Credit Card,2024-02-12,4.7,5200.0
10,1011,Amit Kumar,Delhi,Electronics,Tablet,18000.0,1,UPI,2024-02-15,4.4,18000.0
11,1012,Pooja Hegde,Mumbai,Clothing,Dress,2800.0,2,Credit Card,2024-02-18,4.0,5600.0
12,1013,Siddharth Roy,Bengaluru,Electronics,Monitor,14000.0,1,Net Banking,2024-02-20,4.5,14000.0
13,1014,Riya Sen,Hyderabad,Home & Kitchen,Coffee Maker,4100.0,1,UPI,2024-02-22,4.2,4100.0
14,1015,Deepak Verma,Pune,Clothing,Shirt,1500.0,4,Debit Card,2024-02-25,3.9,6000.0