# Insert Data

In [55]:
import pandas as pd

In [56]:
var  = pd.DataFrame({'A':[1,3,5,7,11], 'B' : [2,4,6,8,10]})
var

    A   B
0   1   2
1   3   4
2   5   6
3   7   8
4  11  10

In [57]:
var.insert(1,'python',var['A']) # (index.column_name,value)
var

    A  python   B
0   1       1   2
1   3       3   4
2   5       5   6
3   7       7   8
4  11      11  10

In [58]:
var.insert( 1, 'java',[9,7,5,3,1])
var

    A  java  python   B
0   1     9       1   2
1   3     7       3   4
2   5     5       5   6
3   7     3       7   8
4  11     1      11  10

In [59]:
var['C'] = var['A'][:3]
var

    A  java  python   B    C
0   1     9       1   2  1.0
1   3     7       3   4  3.0
2   5     5       5   6  5.0
3   7     3       7   8  NaN
4  11     1      11  10  NaN

# Inserting Data

In [60]:
var1 =var.pop('B')
var1
var

    A  java  python    C
0   1     9       1  1.0
1   3     7       3  3.0
2   5     5       5  5.0
3   7     3       7  NaN
4  11     1      11  NaN

In [61]:
del var['java']
var

    A  python    C
0   1       1  1.0
1   3       3  3.0
2   5       5  5.0
3   7       7  NaN
4  11      11  NaN